### ISSUE TITLE
Question json

### ISSUE THREAD

**Issue by ThomasTSWD** [kewinMarchand/wp-rest#52]
Hello ! dans quel fichier tu traites le json du wp ?

**Comment by kewinMarchand** [comment]
Hello. Pas sur de capter la question.

On récup la data ici: https://github.com/kewinMarchand/wp-rest/blob/master/src/pages/Home.tsx#L21 
On la stocke ici : https://github.com/kewinMarchand/wp-rest/blob/master/src/contexts/store.tsx. 
Les getters sont définis ici : https://github.com/kewinMarchand/wp-rest/blob/master/src/client/apiConsumer.ts

**Comment by ThomasTSWD** [comment]
Merci
